### ISSUE TITLE
add /DiscordBridge:reload command

### ISSUE THREAD

**Issue by 1271** [PintsizedSix40/DiscordBridge#2]
Hi
If the js bot crashes or I need to reload the configuration file, it would be nice to be able to at least manually reload the plugin without rebooting the server.
It would also be nice if the plugin tried to connect to the bot every N seconds if it is not connected to the bot (it can be configured in the config)

To all other.
I don’t understand why the `/setplayer <name>` command is intended
She does ... nothing)

Thank.

**Comment by PintsizedSix40** [comment]
Hello,
I will add these features when I can.
As for the /setplayer command, it is meant to be used after running |setplayer on Discord. |setplayer will give you a command to run.
I will also be adding a features/usage list, and the help command will be implemented soon.

**Comment by PintsizedSix40** [comment]
Alright, 639da10 should add all of these features if it works. I added /disbreload and /disbreconnect to reload & reconnect the server to the bot. discordbridge.reload or discordbridge.* or being op should work to grant access to these commands. I will create a new release once the |help command is actully implemented.

**Comment by 1271** [comment]
> As for the /setplayer command, it is meant to be used after running |setplayer on Discord. |setplayer will give you a command to run

Chat works even without these commands. )

And I have another case.
If you use the authorization plugin on the server, then the player’s messages do not enter the game chat until the login, but they get into the chat discord =)

**Comment by PintsizedSix40** [comment]
What exactly is the authorization plugin? I'm assuming it's any plugin that requires a user to login/register prior to being able to play. I will add a commit to change my event's priority to monitor so that it will only get triggered if the chat message will go through. I'll also create some issues with lists of what needs to be implemented.

Setplayer is meant for linking a person's discord and mc account, so they can run commands like |bal to check their balance.

**Comment by 1271** [comment]
> Setplayer is meant for linking ...

Thanks I got it )
Great.

> What exactly is the authorization plugin?

LoginSecurity

But as far as I know, they all work in about the same way and simply do not let the text into the chat :-)

**Comment by PintsizedSix40** [comment]
c771e99 should fix this, as it causes it's event manager to be fired last, so I'll only handle player chat if no plugin canceled the chat event.

**Comment by 1271** [comment]
Thx =)
